openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: bospjhobkfoyarkxcxtcnj
                lastname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: sj
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: mohammad11@example.org
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: '"%A&3*+`G@3BfJJO'
              required:
                - firstname
                - lastname
                - email
                - password
      security: []
  /api/v1/book:
    post:
      summary: ''
      operationId: postApiV1Book
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vkuyg
                author:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: lfcbvkjhveischjzlutxj
                dateOfPublication:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-12-03T08:20:36'
              required:
                - title
                - author
                - dateOfPublication
      security: []
    put:
      summary: ''
      operationId: putApiV1Book
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/book/{id}':
    delete:
      summary: ''
      operationId: deleteApiV1BookId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the book.'
        example: ipsa
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
